version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
    restart: always
    networks:
      - network1
  postgres:
    container_name: postgres
    image: postgres:13
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5433
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - network1

volumes:
  pgdata:

networks:
  network1:
